import {z} from 'zod';
export const money=(n:number,currency='PKR')=>new Intl.NumberFormat('en-PK',{style:'currency',currency,maximumFractionDigits:2}).format(n/100);
const text=(max:number)=>z.string().trim().max(max);
export const slug=z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(120);
export const lineSchema=z.object({product_id:z.uuid(),variant_id:z.uuid().nullable(),quantity:z.number().int().min(1).max(99)});
export const checkoutSchema=z.object({key:z.uuid(),items:z.array(lineSchema).min(1).max(50),name:text(100).min(2),phone:text(30).min(8),email:z.union([z.email(),z.literal('')]),region:text(100).min(2),city:text(100).min(2),address:text(500).min(8),landmark:text(200),notes:text(1000)});
export const productSchema=z.object({id:z.uuid().optional(),name:text(160).min(2),slug,short_description:text(300),description:text(10000),specifications:text(5000),category_id:z.uuid().nullable(),price:z.number().int().min(0).max(100000000),compare_at:z.number().int().min(0).max(100000000).nullable(),shipping_fee:z.number().int().min(0).max(100000000).nullable(),sku:text(80).min(1),stock:z.number().int().min(0).max(1000000),status:z.enum(['draft','active','archived']),featured:z.boolean(),bestseller:z.boolean(),seo_title:text(160),seo_description:text(300)}).refine(p=>p.compare_at===null||p.compare_at>p.price,{message:'Compare-at price must exceed selling price',path:['compare_at']});
export const statuses=['Pending','Confirmed','Processing','Shipped','Delivered','Cancelled','Returned'] as const;
export function canTransition(from:string,to:string){return ({Pending:['Confirmed','Cancelled'],Confirmed:['Processing','Cancelled'],Processing:['Shipped','Cancelled'],Shipped:['Delivered','Returned'],Delivered:['Returned']} as Record<string,string[]>)[from]?.includes(to)??false;}
export const defaults={hero_product_slug:'rechargeable-electric-heating-pad-for-period-pain-relief-heated-waist-belly-belt-for-women-girls',side_banner_one_slug:'dancing-talking-cactus-toy',side_banner_two_slug:'vintage-t9-rechargeable-hair-trimmer',poster_image:'',poster_title:'Best seller',poster_eyebrow:'EVERYDAY COMFORT',poster_headline:'FLAME HUMIDIFIER',poster_link:'/products/rgb-flame-humidifier-and-aroma-diffuser',hero_link:'/shop',brand_name:'',announcement:'A considered collection. Coming soon.',hero_title:'Good things are worth waiting for.',hero_copy:'A new collection is taking shape. Thoughtfully selected, beautifully made, and soon yours to discover.',hero_image:'',story_title:'Fewer things. More meaning.',story_copy:'A space for pieces with purpose. Our collection and the story behind it will be here soon.',logo:'',favicon:'',support_email:'',support_phone:'',currency:'PKR',locale:'en-PK',phone_pattern:'^(?:\\+92|0)3[0-9]{9}$',cod_instructions:'Pay in cash when your order arrives.',delivery_estimate:'Delivery details will be confirmed with your order.',promotion:'',social_links:'',policies_reviewed:false,about:'Our story is being prepared.',contact:'Support contact details will be available before launch.',faq:'Frequently asked questions will be available before launch.','shipping-returns':'Shipping and returns policy is pending business review.',privacy:'Privacy policy is pending business review.',terms:'Terms of service are pending business review.'};
export type Settings=typeof defaults;
export type Product=z.infer<typeof productSchema>&{id:string;updated_at:string;product_images:Media[];product_variants:Variant[]};
export type Media={id:string;url:string;alt:string;position:number;media_type?:'image'|'video'};
export type Variant={id:string;name:string;sku:string;price:number;stock:number;active:boolean};
export type Category={id:string;name:string;slug:string;description:string;image:string;seo_title:string;seo_description:string;position:number;active:boolean};
export type CartLine=z.infer<typeof lineSchema>&{name:string;price:number;image:string;slug:string};
