import {test,expect} from '@playwright/test';
test.setTimeout(180000);
test('shopping routes render and cart drawer works',async({page})=>{await page.setViewportSize({width:1440,height:900});for(const path of ['/shop','/collections','/cart','/checkout','/track','/admin/login','/about','/shipping-returns']){await page.goto(path);await expect(page.locator('h1').first()).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);}await page.goto('/');await expect(page.getByText('Latest products').first()).toBeVisible();await page.getByRole('button',{name:'Shopping bag, 0 items'}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);});
test('themed add-to-bag button confirms success',async({page})=>{await page.goto('/products/vintage-t9-rechargeable-hair-trimmer');const button=page.locator('.addly-button').first();await button.click();await expect(button).toHaveClass(/added/);await expect(page.getByRole('dialog')).toBeVisible();});
test('admin routes redirect without authentication',async({page})=>{await page.goto('/admin');await expect(page).toHaveURL(/\/admin\/login$/,{timeout:30000});});
test('filters persist in URL and can be cleared',async({page})=>{await page.setViewportSize({width:1440,height:900});await page.goto('/shop');await expect(page.getByText(/\d+ products?/)).toBeVisible();await page.getByLabel('Search',{exact:true}).fill('linen');await page.getByRole('button',{name:'Apply filters'}).click();await expect(page).toHaveURL(/search=linen/);await page.reload();await expect(page.getByLabel('Search',{exact:true})).toHaveValue('linen');await page.getByRole('link',{name:'Remove search filter'}).click();await expect(page.getByLabel('Search',{exact:true})).toHaveValue('');});
test('anonymous cart survives reload and remains editable',async({page})=>{await page.goto('/');await page.evaluate(()=>localStorage.setItem('store-cart-v1',JSON.stringify({state:{items:[{product_id:'22222222-2222-4222-8222-222222222222',variant_id:null,quantity:2,name:'Test-only product',price:12345,image:'',slug:'test-only'}]},version:0})));await page.goto('/cart');await expect(page.getByText('Test-only product',{exact:true})).toBeVisible();await page.getByLabel('Quantity for Test-only product').fill('3');await page.reload();await expect(page.getByLabel('Quantity for Test-only product')).toHaveValue('3');await page.getByRole('button',{name:'Remove',exact:true}).click();await expect(page.getByRole('heading',{name:'Your bag has room for something good.'})).toBeVisible();});
test('private confirmation requires receipt',async({page})=>{await page.goto('/order-confirmation/1234567890ABCDEF1234');await expect(page.getByRole('heading',{name:'Find your order'})).toBeVisible();});
test('customer can complete delivery details and receive a COD total',async({page})=>{await page.goto('/products/vintage-t9-rechargeable-hair-trimmer');await page.locator('.addly-button').first().click();await page.getByRole('link',{name:/Continue to checkout/}).click();await page.getByLabel('Full name').fill('Test Customer');await page.getByLabel('Mobile number').fill('03001234567');await page.getByLabel('Province / region').selectOption('Punjab');await page.getByLabel('City').fill('Lahore');await page.getByLabel('Complete delivery address').fill('12 Test Street, Lahore');await page.getByRole('button',{name:'Preview delivery total'}).click();await expect(page.getByText('Pay on arrival',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Confirm order — pay on delivery'})).toBeEnabled();});
