import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import {beforeAll,afterAll,describe,it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
let db:PGlite;
const admin='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
const buyer='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
beforeAll(async()=>{db=new PGlite();await db.exec(`
create role anon; create role authenticated; create role service_role;
create schema auth;create schema extensions;create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit int,allowed_mime_types text[]);create table storage.objects(id uuid,bucket_id text);alter table storage.objects enable row level security;
-- PGlite does not ship pgcrypto. These test-only substitutes support SQL execution;
-- they are not cryptographic implementations and never ship in the migration.
create function gen_random_bytes(n int) returns bytea language sql as $$select decode(substr(repeat(md5(random()::text),10),1,n*2),'hex')$$;
create function extensions.digest(value text,algorithm text) returns bytea language sql immutable as $$select decode(md5(value),'hex')$$;
`);await db.exec(readFileSync('supabase/migrations/001_store.sql','utf8').replace('create extension if not exists pgcrypto;',''));await db.exec(readFileSync('supabase/migrations/003_product_media_shipping.sql','utf8')); await db.exec(`grant usage on schema public,auth to anon,authenticated;grant select,insert,update,delete on all tables in schema public to anon,authenticated;insert into auth.users values('${admin}'),('${buyer}');insert into profiles values('${admin}','admin'),('${buyer}','customer');update store_settings set value='{"policies_reviewed":true,"currency":"PKR","phone_pattern":"^(0)3[0-9]{9}$"}';insert into shipping_rules(region,city,fee) values('','',30000),('Punjab','Lahore',15000);`);},60000);
afterAll(async()=>{await db?.close();});
async function product(stock=5){const id=randomUUID();await db.query(`insert into products(id,name,slug,sku,price,stock,status) values($1::uuid,'Test product',$1::text,$1::text,125000,$2,'active')`,[id,stock]);return id;}
function payload(id:string,quantity=1){return {key:randomUUID(),items:[{product_id:id,variant_id:null,quantity}],name:'Test buyer',phone:'03001234567',email:'',region:'Punjab',city:'Lahore',address:'123 Test Street',landmark:'',notes:''};}
async function place(p:ReturnType<typeof payload>){const {rows}=await db.query<{result:{order_number:string}}>(`select place_order($1::jsonb,'test-receipt') as result`,[JSON.stringify(p)]);return rows[0].result.order_number;}
describe('database integrity',()=>{
it('calculates authoritative totals and decrements inventory exactly once for retries',async()=>{const id=await product();const p=payload(id,2);const number=await place(p);expect(await place(p)).toBe(number);const {rows}=await db.query<{total:number;shipping:number;subtotal:number}>(`select total,shipping,subtotal from orders where order_number=$1`,[number]);expect(Number(rows[0].total)).toBe(265000);expect(Number(rows[0].shipping)).toBe(15000);expect((await db.query<{stock:number}>(`select stock from products where id=$1`,[id])).rows[0].stock).toBe(3);});
it('honors free delivery configured for a product',async()=>{const id=await product();await db.query(`update products set shipping_fee=0 where id=$1`,[id]);const number=await place(payload(id));const {rows}=await db.query<{shipping:number}>(`select shipping from orders where order_number=$1`,[number]);expect(Number(rows[0].shipping)).toBe(0);});
it('rejects altered replay payloads',async()=>{const id=await product();const p=payload(id);await place(p);await expect(place({...p,quantity:2,items:[{...p.items[0],quantity:2}]} as ReturnType<typeof payload>)).rejects.toThrow('changed');});
it('rolls back the entire order when any line exceeds stock',async()=>{const id=await product(1);const p=payload(id,2);await expect(place(p)).rejects.toThrow('insufficient stock');expect((await db.query<{stock:number}>(`select stock from products where id=$1`,[id])).rows[0].stock).toBe(1);expect((await db.query(`select id from orders where idempotency_key=$1`,[p.key])).rows).toHaveLength(0);});
it('prevents two orders from consuming the last unit',async()=>{const id=await product(1);const results=await Promise.allSettled([place(payload(id)),place(payload(id))]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect((await db.query<{stock:number}>(`select stock from products where id=$1`,[id])).rows[0].stock).toBe(0);});
it('rejects duplicate lines whose combined quantity exceeds stock',async()=>{const id=await product(1);const p=payload(id);p.items.push({...p.items[0]});await expect(place(p)).rejects.toThrow('insufficient stock');expect((await db.query<{stock:number}>(`select stock from products where id=$1`,[id])).rows[0].stock).toBe(1);});
it('requires a real active variant belonging to the product',async()=>{const id=await product();const variant=randomUUID();await db.query(`insert into product_variants(id,product_id,name,sku,price,stock) values($1::uuid,$2,'Large',$1::text,150000,2)`,[variant,id]);await expect(place(payload(id))).rejects.toThrow('Choose a product option');const p=payload(id);const withVariant={...p,items:[{...p.items[0],variant_id:variant}]};await db.query(`select place_order($1::jsonb,'test-receipt')`,[JSON.stringify(withVariant)]);expect((await db.query<{stock:number}>(`select stock from product_variants where id=$1`,[variant])).rows[0].stock).toBe(1);});
it('keeps snapshots unchanged after product edits and prevents snapshot mutation',async()=>{const id=await product();const number=await place(payload(id));await db.query(`update products set name='Changed',price=1 where id=$1`,[id]);const {rows}=await db.query<{name:string;price:number}>(`select i.name,i.price from order_items i join orders o on i.order_id=o.id where o.order_number=$1`,[number]);expect(rows[0]).toEqual({name:'Test product',price:125000});await expect(db.query(`update order_items set price=0 where product_id=$1`,[id])).rejects.toThrow('immutable');});
it('enforces RLS for anonymous catalog and private orders',async()=>{await db.exec('set role anon');try{expect((await db.query('select * from orders')).rows).toHaveLength(0);await expect(db.exec(`insert into categories(name,slug) values('Forbidden','forbidden')`)).rejects.toThrow();await expect(db.exec(`select place_order('{}','x')`)).rejects.toThrow('permission denied');expect((await db.query('select * from products')).rows.length).toBeGreaterThan(0);}finally{await db.exec('reset role');}});
it('denies ordinary authenticated users admin writes and role escalation',async()=>{await db.exec(`set role authenticated;select set_config('request.jwt.claim.sub','${buyer}',false)`);try{expect((await db.query('select * from orders')).rows).toHaveLength(0);await expect(db.exec(`insert into categories(name,slug) values('Forbidden','forbidden')`)).rejects.toThrow();await db.exec(`update profiles set role='admin' where id='${buyer}'`);expect((await db.query<{role:string}>('select role from profiles')).rows[0].role).toBe('customer');}finally{await db.exec('reset role');}});
it('audits status changes, restores stock once and rejects invalid transitions',async()=>{const id=await product(2);const number=await place(payload(id));const {rows}=await db.query<{id:string}>(`select id from orders where order_number=$1`,[number]);const orderId=rows[0].id;await db.exec(`set role authenticated;select set_config('request.jwt.claim.sub','${admin}',false)`);try{await expect(db.query(`select change_order_status($1,'Delivered')`,[orderId])).rejects.toThrow('Invalid');await db.query(`select change_order_status($1,'Cancelled')`,[orderId]);await expect(db.query(`select change_order_status($1,'Cancelled')`,[orderId])).rejects.toThrow('Invalid');}finally{await db.exec('reset role');}expect((await db.query<{stock:number}>(`select stock from products where id=$1`,[id])).rows[0].stock).toBe(2);expect((await db.query(`select * from order_status_history where order_id=$1 and changed_by=$2`,[orderId,admin])).rows).toHaveLength(1);});
it('limits repeated requests in persistent database state',async()=>{for(let i=0;i<3;i++)expect((await db.query<{ok:boolean}>(`select consume_rate('test-rate',3,60) as ok`)).rows[0].ok).toBe(true);expect((await db.query<{ok:boolean}>(`select consume_rate('test-rate',3,60) as ok`)).rows[0].ok).toBe(false);});
});

