'use server';
import {z} from 'zod';
import {redirect} from 'next/navigation';
import {revalidatePath} from 'next/cache';
import {db,requireAdmin} from '@/lib/db';
import {productSchema,slug,defaults} from '@/lib/model';
import {rate} from '@/lib/security';
type Result={error?:string;success?:string;id?:string};
export async function login(_previous:Result,form:FormData):Promise<Result>{let ok=false;try{const email=z.email().parse(form.get('email'));const password=z.string().min(1).max(200).parse(form.get('password'));await rate('login',email.toLowerCase(),8);const client=await db();const {data,error}=await client.auth.signInWithPassword({email,password});if(error||!data.user)throw new Error('Email or password is incorrect.');const {data:profile}=await client.from('profiles').select('role').eq('id',data.user.id).single();if(profile?.role!=='admin'){await client.auth.signOut();throw new Error('This user does not have admin access.');}ok=true;}catch(e){return {error:e instanceof Error?e.message:'Unable to sign in. Retry.'};}if(ok)redirect('/admin');return {};}
export async function logout(){const client=await db();await client.auth.signOut();redirect('/admin/login');}
export async function changePassword(_previous:Result,form:FormData):Promise<Result>{try{const client=await requireAdmin();const {data:{user}}=await client.auth.getUser();if(!user?.email)throw new Error('Admin account could not be verified.');await rate('change-password',user.id,5);const current=z.string().min(1).max(200).parse(form.get('current_password'));const next=z.string().min(10,'New password must be at least 10 characters.').max(200).parse(form.get('new_password'));const confirmation=z.string().parse(form.get('confirm_password'));if(next!==confirmation)throw new Error('New passwords do not match.');if(current===next)throw new Error('Choose a different new password.');const {error:signInError}=await client.auth.signInWithPassword({email:user.email,password:current});if(signInError)throw new Error('Current password is incorrect.');const {error}=await client.auth.updateUser({password:next});if(error)throw error;return{success:'Admin password changed successfully.'};}catch(e){return{error:e instanceof Error?e.message:'Password could not be changed.'};}}
const categorySchema=z.object({id:z.uuid().optional(),name:z.string().trim().min(2).max(160),slug,description:z.string().trim().max(5000),image:z.union([z.url().startsWith('https://'),z.literal('')]),seo_title:z.string().max(160),seo_description:z.string().max(300),position:z.number().int().min(0),active:z.boolean()});
export async function saveProduct(input:unknown):Promise<Result>{const client=await requireAdmin();try{const p=productSchema.and(z.object({expected_updated_at:z.string().optional()})).parse(input);const {id,expected_updated_at,...values}=p;const write=async(v:typeof values|Omit<typeof values,'shipping_fee'>)=>await(id?client.from('products').update(v).eq('id',id).eq('updated_at',expected_updated_at||'1970-01-01T00:00:00Z'):client.from('products').insert(v)).select('id').single();let result=await write(values);if(result.error?.message.includes('shipping_fee')){const {shipping_fee,...compatible}=values;void shipping_fee;result=await write(compatible);}const {data,error}=result;if(error)throw new Error(error.code==='23505'?'Slug or SKU already exists.':error.code==='PGRST116'?'This product changed while you were editing. Reload it before saving to preserve current inventory.':error.message);revalidatePath('/','layout');return {success:'Product saved.',id:data.id};}catch(e){return{error:e instanceof Error?e.message:'Product could not be saved.'};}}
export async function duplicateProduct(id:string):Promise<Result>{const client=await requireAdmin();try{z.uuid().parse(id);const {data,error}=await client.from('products').select('*').eq('id',id).single();if(error)throw error;const {id:oldId,created_at,updated_at,...values}=data;void oldId;void created_at;void updated_at;const suffix=crypto.randomUUID().slice(0,8);const {data:copy,error:copyError}=await client.from('products').insert({...values,name:values.name+' (copy)',slug:values.slug+'-'+suffix,sku:values.sku+'-'+suffix,status:'draft',stock:0}).select('id').single();if(copyError)throw copyError;revalidatePath('/admin/products');return{success:'Draft duplicated. Add inventory and images before activating.',id:copy.id};}catch(e){return{error:e instanceof Error?e.message:'Could not duplicate product.'};}}
export async function deleteProduct(id:string):Promise<Result>{const client=await requireAdmin();try{z.uuid().parse(id);const {count,error:orderError}=await client.from('order_items').select('id',{count:'exact',head:true}).eq('product_id',id);if(orderError)throw orderError;if(count)throw new Error('This product belongs to an existing order and must be archived instead.');const {data:images,error:imageError}=await client.from('product_images').select('url').eq('product_id',id);if(imageError)throw imageError;const {error:variantError}=await client.from('product_variants').delete().eq('product_id',id);if(variantError)throw variantError;const {error}=await client.from('products').delete().eq('id',id);if(error)throw error;const prefix='/storage/v1/object/public/product-media/';const paths=(images||[]).map(image=>{try{const path=new URL(image.url).pathname;return path.includes(prefix)?decodeURIComponent(path.split(prefix)[1]):'';}catch{return '';}}).filter(Boolean);if(paths.length)await client.storage.from('product-media').remove(paths);revalidatePath('/','layout');return{success:'Product permanently deleted.'};}catch(e){return{error:e instanceof Error?e.message:'Could not delete product.'};}}
export async function saveCategory(input:unknown):Promise<Result>{const client=await requireAdmin();try{const {id,...values}=categorySchema.parse(input);const {error}=await(id?client.from('categories').update(values).eq('id',id):client.from('categories').insert(values));if(error)throw error;revalidatePath('/','layout');return{success:'Collection saved.'};}catch(e){return{error:e instanceof Error?e.message:'Could not save collection. Check for a duplicate slug.'};}}
export async function deleteCategory(id:string):Promise<Result>{const client=await requireAdmin();try{z.uuid().parse(id);const {error}=await client.from('categories').delete().eq('id',id);if(error)throw new Error('Reassign all products before deleting this collection.');revalidatePath('/','layout');return{success:'Collection deleted.'};}catch(e){return{error:e instanceof Error?e.message:'Could not delete collection.'};}}
export async function saveVariant(input:unknown):Promise<Result>{const client=await requireAdmin();try{const {id,...v}=z.object({id:z.uuid().optional(),product_id:z.uuid(),name:z.string().trim().min(1).max(100),sku:z.string().trim().min(1).max(80),price:z.number().int().min(0).max(100000000),stock:z.number().int().min(0).max(1000000),active:z.boolean()}).parse(input);const {error}=await(id?client.from('product_variants').update(v).eq('id',id):client.from('product_variants').insert(v));if(error)throw error;revalidatePath('/','layout');return{success:'Option saved.'};}catch(e){return{error:e instanceof Error?e.message:'Could not save option.'};}}
export async function saveMedia(input:unknown):Promise<Result>{const client=await requireAdmin();try{const {id,...v}=z.object({id:z.uuid(),alt:z.string().trim().min(1).max(300),position:z.number().int().min(0).max(1000)}).parse(input);const {error}=await client.from('product_images').update(v).eq('id',id);if(error)throw error;revalidatePath('/','layout');return{success:'Image details saved.'};}catch(e){return{error:e instanceof Error?e.message:'Could not save image.'};}}
export async function removeMedia(id:string):Promise<Result>{const client=await requireAdmin();try{z.uuid().parse(id);const {error}=await client.from('product_images').delete().eq('id',id);if(error)throw error;revalidatePath('/','layout');return{success:'Image removed from product.'};}catch(e){return{error:e instanceof Error?e.message:'Could not remove image.'};}}
export async function updateStatus(input:unknown):Promise<Result>{const client=await requireAdmin();try{const p=z.object({id:z.uuid(),status:z.enum(['Confirmed','Processing','Shipped','Delivered','Cancelled','Returned'])}).parse(input);const {error}=await client.rpc('change_order_status',{p_id:p.id,p_status:p.status});if(error)throw error;revalidatePath('/admin','layout');return{success:'Order status updated.'};}catch(e){return{error:e instanceof Error?e.message:'Could not update status.'};}}
export async function saveSettings(input:unknown):Promise<Result>{const client=await requireAdmin();try{const shape=Object.fromEntries(Object.entries(defaults).map(([k,v])=>[k,typeof v==='boolean'?z.boolean():z.string().trim().max(k==='privacy'||k==='terms'||k==='shipping-returns'?30000:10000)]));const values=z.object(shape).parse(input);z.string().regex(/^[A-Z]{3}$/).parse(values.currency);z.string().regex(/^[a-z]{2}-[A-Z]{2}$/).parse(values.locale);new Intl.NumberFormat(String(values.locale),{style:'currency',currency:String(values.currency)});new RegExp(String(values.phone_pattern));for(const key of ['logo','favicon','hero_image','poster_image'])if(values[key])z.url().startsWith('https://').parse(values[key]);if(values.support_email)z.email().parse(values.support_email);const {error}=await client.from('store_settings').update({value:values}).eq('id',1);if(error)throw error;revalidatePath('/','layout');return{success:'Store settings saved.'};}catch(e){return{error:e instanceof Error?e.message:'Could not save settings.'};}}
export async function saveShipping(input:unknown):Promise<Result>{const client=await requireAdmin();try{const {id,...v}=z.object({id:z.uuid().optional(),region:z.string().trim().max(100),city:z.string().trim().max(100),fee:z.number().int().min(0).max(100000000),active:z.boolean()}).parse(input);const {error}=await(id?client.from('shipping_rules').update(v).eq('id',id):client.from('shipping_rules').insert(v));if(error)throw error;revalidatePath('/admin/settings');return{success:'Shipping rule saved.'};}catch(e){return{error:e instanceof Error?e.message:'Could not save shipping rule.'};}}

