'use client';
import {useActionState,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import Image from 'next/image';
import {login,saveProduct,saveCategory,saveVariant,saveMedia,removeMedia,updateStatus,saveSettings,saveShipping,duplicateProduct,deleteProduct,deleteCategory} from '@/app/admin/actions';
import {type Product,type Category,type Settings,type Variant,type Media,canTransition,statuses} from '@/lib/model';
type Result={error?:string;success?:string;id?:string};
export function LoginForm({configured}:{configured:boolean}){const [state,action,pending]=useActionState(login,{});return <form action={action} className="panel stack"><label>Email<input name="email" type="email" autoComplete="username" required/></label><label>Password<input name="password" type="password" autoComplete="current-password" required/></label>{state.error&&<p className="error" role="alert">{state.error}</p>}{!configured&&<p className="notice">Connect Supabase to enable administrator sign-in.</p>}<button className="button" disabled={pending||!configured}>{pending?'Signing in…':'Sign in securely'}</button></form>;}
export function Action({action,children,confirm,danger=false,onSuccess}:{action:()=>Promise<Result>;children:React.ReactNode;confirm?:string;danger?:boolean;onSuccess?:()=>void}){const [result,setResult]=useState<Result>({});const [busy,setBusy]=useState(false);const router=useRouter();return <div><button className={`button secondary${danger?' danger':''}`} disabled={busy} onClick={async()=>{if(confirm&&!window.confirm(confirm))return;setBusy(true);try{const r=await action();setResult(r);if(r.success){onSuccess?.();router.refresh();}}catch{setResult({error:'Request failed. Please retry.'});}finally{setBusy(false);}}}>{busy?'Working…':children}</button><Feedback result={result}/></div>;}
function Feedback({result}:{result:Result}){return <>{result.error&&<p className="error" role="alert">{result.error}</p>}{result.success&&<p className="success" role="status">{result.success}</p>}</>;}
function Form({children,save,label='Save changes'}:{children:React.ReactNode;save:(form:FormData)=>Promise<Result>;label?:string}){const [result,setResult]=useState<Result>({});const [busy,setBusy]=useState(false);const router=useRouter();return <form className="stack admin-form" onSubmit={async e=>{e.preventDefault();const data=new FormData(e.currentTarget);setBusy(true);setResult({});try{const r=await save(data);setResult(r);if(r.success)router.refresh();}catch{setResult({error:'Request failed. Please retry.'});}finally{setBusy(false);}}}>{children}<Feedback result={result}/><button className="button" disabled={busy}>{busy?'Saving…':label}</button></form>;}
const string=(f:FormData,k:string)=>String(f.get(k)||'');
const num=(f:FormData,k:string)=>Number(f.get(k)||0);
const checked=(f:FormData,k:string)=>f.get(k)==='on';
function Field({name,label,value='',type='text',required=false}:{name:string;label:string;value?:string|number;type?:string;required?:boolean}){return <label>{label}<input name={name} type={type} defaultValue={value} required={required} min={type==='number'?0:undefined}/></label>;}
function ProductImagePicker(){const [files,setFiles]=useState<File[]>([]);const input=useRef<HTMLInputElement>(null);const sync=(next:File[])=>{const transfer=new DataTransfer();next.forEach(file=>transfer.items.add(file));if(input.current)input.current.files=transfer.files;setFiles(next);};const add=(selected:FileList|null)=>sync([...files,...Array.from(selected||[])].filter((file,index,all)=>all.findIndex(item=>item.name===file.name&&item.size===file.size)===index));return <div className="admin-image-picker full"><div><strong>Product images</strong><span className="field-help">JPEG, PNG or WebP · maximum 5 MB each</span><div className="admin-image-previews" aria-label={`${files.length} selected image previews`}>{files.map((file,index)=><div className="admin-image-preview" key={file.name+file.size}><Image unoptimized src={URL.createObjectURL(file)} alt={`Selected product preview ${index+1}`} fill sizes="120px"/><span>{index+1}</span><button type="button" className="admin-image-remove" aria-label={`Remove image ${index+1}`} onClick={()=>sync(files.filter((_,item)=>item!==index))}>×</button></div>)}<label className="admin-image-add" aria-label="Add product images"><b>+</b><span>Add images</span><input ref={input} name="image" type="file" accept="image/jpeg,image/png,image/webp" required={!files.length} multiple onChange={e=>add(e.currentTarget.files)}/></label></div></div><Field name="image_alt" label="Describe these product images for customers using screen readers" required/></div>}
export function ProductEditor({product:p,categories}:{product?:Product;categories:Category[]}){
  const router=useRouter();
  const [name,setName]=useState(p?.name||'');
  const [productSlug,setProductSlug]=useState(p?.slug||'');
  const [slugEdited,setSlugEdited]=useState(Boolean(p));
  return <Form label={p?'Save product':'Create product'} save={async f=>{
    if(p&&p.status!=='archived'&&string(f,'status')==='archived'&&!window.confirm('Archive this product? It will disappear from the store. Existing orders remain intact.'))return {};
    const result=await saveProduct({id:p?.id,expected_updated_at:p?.updated_at,name:string(f,'name'),slug:string(f,'slug'),sku:string(f,'sku'),short_description:string(f,'short_description'),description:string(f,'description'),specifications:string(f,'specifications'),category_id:string(f,'category_id')||null,price:Math.round(num(f,'price')*100),compare_at:string(f,'compare_at')?Math.round(num(f,'compare_at')*100):null,stock:num(f,'stock'),status:string(f,'status'),featured:checked(f,'featured'),bestseller:checked(f,'bestseller'),seo_title:string(f,'seo_title'),seo_description:string(f,'seo_description')});
    if(result.id&&!p){
      const files=f.getAll('image').filter((file):file is File=>file instanceof File&&file.size>0);
      for(const [index,file] of files.entries()){const upload=new FormData();upload.set('product_id',result.id);upload.set('file',file);upload.set('alt',`${string(f,'image_alt')||string(f,'name')}${files.length>1?` ${index+1}`:''}`);const response=await fetch('/api/admin/upload',{method:'POST',body:upload});if(!response.ok){router.push('/admin/products/'+result.id+'?imageUpload=failed');return{success:`Product created. ${index} of ${files.length} images uploaded; please retry the remaining images below.`,id:result.id};}}
      router.push('/admin/products/'+result.id);
    }
    return result;
  }}>
    {!p&&<div className="admin-form-intro"><strong>Add a new product</strong><span>Complete the three simple steps below. Optional details can be added later.</span></div>}
    {!p&&<fieldset className="fields admin-step"><legend><span>1</span> Product image</legend><ProductImagePicker/></fieldset>}
    <fieldset className="fields admin-step"><legend><span>{p?'1':'2'}</span> Product details</legend><label>Product name<input name="name" value={name} required onChange={e=>{const next=e.target.value;setName(next);if(!slugEdited)setProductSlug(next.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''));}}/></label><label>Page address <span className="field-help">Generated automatically; edit only if needed.</span><input name="slug" value={productSlug} required onChange={e=>{setSlugEdited(true);setProductSlug(e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,''));}}/></label><Field name="sku" label="SKU / inventory code" value={p?.sku} required/><label>Collection<select name="category_id" defaultValue={p?.category_id||''}><option value="">No collection</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="full">Short description <span className="field-help">This appears on product cards.</span><textarea name="short_description" defaultValue={p?.short_description} placeholder="Describe the product in one clear sentence."/></label><details className="full admin-optional"><summary>More product information <span>Optional</span></summary><div className="fields"><label className="full">Full description<textarea name="description" defaultValue={p?.description} placeholder="Explain benefits, use and important details."/></label><label className="full">Specifications<textarea name="specifications" defaultValue={p?.specifications} placeholder="Size, material, included items and care instructions."/></label></div></details></fieldset>
    <fieldset className="fields admin-step"><legend><span>{p?'2':'3'}</span> Price, stock and publishing</legend><label>Selling price (PKR)<input name="price" type="number" step="0.01" min="0" required defaultValue={p?p.price/100:''}/></label><label>Original price <span className="field-help">Optional; shown crossed out.</span><input name="compare_at" type="number" step="0.01" min="0" defaultValue={p?.compare_at?p.compare_at/100:''}/></label><Field name="stock" label="Available quantity" type="number" value={p?.stock||0}/><label>Publish status<select name="status" defaultValue={p?.status||'draft'}><option value="draft">Save as draft</option><option value="active">Publish in store</option><option value="archived">Archive product</option></select></label><label><input name="featured" type="checkbox" defaultChecked={p?.featured}/>Feature on the storefront</label><label><input name="bestseller" type="checkbox" defaultChecked={p?.bestseller}/>Mark as a customer favourite</label></fieldset>
    <details className="admin-optional"><summary>Google search appearance <span>Optional</span></summary><div className="fields"><Field name="seo_title" label="Search result title" value={p?.seo_title}/><Field name="seo_description" label="Search result description" value={p?.seo_description}/></div></details>
    {p&&<p className="notice">Use the Product images section below to add, describe, reorder or remove images.</p>}
  </Form>;
}
export function ProductTools({id}:{id:string}){const router=useRouter();return <section className="panel stack danger-zone"><div><h2>Product actions</h2><p className="muted">Duplicate this product as a draft, or permanently delete it if it has never been ordered.</p></div><div className="row"><Action action={()=>duplicateProduct(id)}>Duplicate as draft</Action><Action danger action={()=>deleteProduct(id)} confirm="Permanently delete this product and its images? This cannot be undone." onSuccess={()=>router.push('/admin/products')}>Delete product</Action></div></section>;}
export function CategoryEditor({category:c}:{category?:Category}){return <Form label={c?'Save collection':'Create collection'} save={f=>saveCategory({id:c?.id,name:string(f,'name'),slug:string(f,'slug'),description:string(f,'description'),image:string(f,'image'),seo_title:string(f,'seo_title'),seo_description:string(f,'seo_description'),position:num(f,'position'),active:checked(f,'active')})}><div className="fields"><Field name="name" label="Name" value={c?.name} required/><Field name="slug" label="Slug" value={c?.slug} required/><Field name="image" label="Editorial image URL (optional)" value={c?.image}/><Field name="position" label="Display order" type="number" value={c?.position||0}/><label className="full">Description<textarea name="description" defaultValue={c?.description}/></label><Field name="seo_title" label="SEO title" value={c?.seo_title}/><Field name="seo_description" label="SEO description" value={c?.seo_description}/><label><input name="active" type="checkbox" defaultChecked={c?.active??true}/>Active</label></div></Form>;}
export function CategoryDelete({id}:{id:string}){return <Action action={()=>deleteCategory(id)} confirm="Delete this collection? Products must be reassigned first.">Delete collection</Action>;}
export function VariantEditor({productId,variant:v}:{productId:string;variant?:Variant}){return <Form label={v?'Save option':'Add option'} save={f=>saveVariant({id:v?.id,product_id:productId,name:string(f,'name'),sku:string(f,'sku'),price:Math.round(num(f,'price')*100),stock:num(f,'stock'),active:checked(f,'active')})}><div className="fields"><Field name="name" label="Option name" value={v?.name} required/><Field name="sku" label="Option SKU" value={v?.sku} required/><label>Option price<input name="price" type="number" min="0" step="0.01" defaultValue={v?v.price/100:0}/></label><Field name="stock" label="Option stock" type="number" value={v?.stock||0}/><label><input name="active" type="checkbox" defaultChecked={v?.active??true}/>Active</label></div></Form>;}
export function MediaEditor({media:m}:{media:Media}){return <div className="stack"><Form save={f=>saveMedia({id:m.id,alt:string(f,'alt'),position:num(f,'position')})}><div className="media-row"><Image unoptimized src={m.url} alt={m.alt} width={70} height={88}/><Field name="alt" label="Image description" value={m.alt} required/><Field name="position" label="Position" value={m.position} type="number"/></div></Form><Action action={()=>removeMedia(m.id)} confirm="Remove this image from the product?">Remove image</Action></div>;}
export function Upload({id}:{id:string}){return <Form label="Upload images" save={async f=>{const files=f.getAll('file').filter((file):file is File=>file instanceof File&&file.size>0);const alt=string(f,'alt');for(const [index,file] of files.entries()){const upload=new FormData();upload.set('product_id',id);upload.set('file',file);upload.set('alt',`${alt}${files.length>1?` ${index+1}`:''}`);const response=await fetch('/api/admin/upload',{method:'POST',body:upload});const data=await response.json();if(!response.ok)return{error:`${index} of ${files.length} images uploaded. ${data.error}`};}return{success:`${files.length} image${files.length===1?'':'s'} uploaded.`};}}><label>Product images · JPEG, PNG, WebP, up to 5 MB each<input name="file" type="file" accept="image/jpeg,image/png,image/webp" required multiple/></label><Field name="alt" label="Descriptive alt text" required/></Form>;}
export function StatusEditor({id,status}:{id:string;status:string}){return <Form label="Update order status" save={async f=>{const next=string(f,'status');if(['Cancelled','Returned'].includes(next)&&!window.confirm(`${next} this order? Inventory will be restored once and the change will be recorded.`))return{};return updateStatus({id,status:next});}}><label>Next status<select name="status" required defaultValue=""><option value="" disabled>Choose next status</option>{statuses.filter(s=>canTransition(status,s)).map(s=><option key={s}>{s}</option>)}</select></label></Form>;}
export function SettingsEditor({settings:s,bannerProducts=[]}:{settings:Settings;bannerProducts?:{slug:string;name:string}[]}){const long=['hero_copy','story_copy','cod_instructions','about','contact','faq','shipping-returns','privacy','terms'];const banners=['hero_product_slug','side_banner_one_slug','side_banner_two_slug'];return <Form save={f=>saveSettings(Object.fromEntries(Object.entries(s).map(([k,v])=>[k,typeof v==='boolean'?checked(f,k):string(f,k)])))}><div className="fields">{Object.entries(s).map(([k,v])=>typeof v==='boolean'?<label key={k} className="full"><input type="checkbox" name={k} defaultChecked={v}/>Business policies reviewed and ready for orders</label>:banners.includes(k)?<label key={k}>{k.replaceAll('_',' ')}<select name={k} defaultValue={v}>{bannerProducts.map(p=><option key={p.slug} value={p.slug}>{p.name}</option>)}</select></label>:<label key={k} className={long.includes(k)?'full':''}>{k.replaceAll('_',' ').replaceAll('-',' ')}{long.includes(k)?<textarea name={k} defaultValue={v}/>:<input name={k} defaultValue={v}/>}</label>)}</div><p className="notice">Banner product selections update the homepage. Review brand, support details, shipping coverage, and all policies before enabling orders.</p></Form>;}
export function ShippingEditor({rule:r}:{rule?:{id:string;region:string;city:string;fee:number;active:boolean}}){return <Form label={r?'Save shipping rule':'Add shipping rule'} save={f=>saveShipping({id:r?.id,region:string(f,'region'),city:string(f,'city'),fee:Math.round(num(f,'fee')*100),active:checked(f,'active')})}><div className="fields"><Field name="region" label="Region (blank = all)" value={r?.region}/><Field name="city" label="City (blank = all)" value={r?.city}/><label>Delivery fee<input name="fee" type="number" min="0" step="0.01" defaultValue={r?r.fee/100:0}/></label><label><input name="active" type="checkbox" defaultChecked={r?.active??true}/>Active</label></div></Form>;}


