'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {useForm} from 'react-hook-form';
import {zodResolver} from '@hookform/resolvers/zod';
import {z} from 'zod';
import Link from 'next/link';
import {useCart} from '@/lib/cart';
import {checkoutSchema,money,type Settings} from '@/lib/model';
import {Empty} from './store';
const formSchema=checkoutSchema.omit({items:true,key:true});
type Form=z.infer<typeof formSchema>;
type Quote={items:{name:string;quantity:number;price:number}[];subtotal:number;shipping:number;total:number;currency:string};
export function Checkout({settings:s}:{settings:Settings}){const cart=useCart();const [error,setError]=useState('');const [quote,setQuote]=useState<Quote|null>(null);const [quoting,setQuoting]=useState(false);const [placing,setPlacing]=useState(false);const router=useRouter();const {register,handleSubmit,getValues,formState:{errors}}=useForm<Form>({resolver:zodResolver(formSchema),defaultValues:{name:'',phone:'',email:'',region:'',city:'',address:'',landmark:'',notes:''}});const items=()=>cart.items.map(({product_id,variant_id,quantity})=>({product_id,variant_id,quantity}));async function calculate(){setQuoting(true);setError('');setQuote(null);try{const {region,city}=getValues();const response=await fetch('/api/quote',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items:items(),region,city})});const data=await response.json();if(!response.ok)throw new Error(data.error);setQuote(data);return data as Quote;}catch(e){setError(e instanceof Error?e.message:'Unable to calculate totals. Retry.');return null;}finally{setQuoting(false);}}
async function submit(values:Form){if(placing)return;setPlacing(true);setError('');try{
if(!new RegExp(s.phone_pattern).test(values.phone.replace(/[\s()-]/g,'')))throw new Error('Enter a valid mobile number for '+s.locale+'.');
const payload=JSON.stringify({...values,items:items()});
const saved=sessionStorage.getItem('checkout-attempt');
let attempt:{key:string;receipt:string;payload:string}|null=saved?JSON.parse(saved):null;
if(attempt&&attempt.payload!==payload)throw new Error('This checkout has an unresolved attempt. Retry with the original details or track your order before starting again.');
if(!attempt){const fresh=await calculate();if(!fresh)return;if(!quote||quote.total!==fresh.total||JSON.stringify(quote.items)!==JSON.stringify(fresh.items)){setError('Your total is ready. Please review the order summary, then place your order.');return;}
const bytes=crypto.getRandomValues(new Uint8Array(32));attempt={key:crypto.randomUUID(),receipt:Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join(''),payload};sessionStorage.setItem('checkout-attempt',JSON.stringify(attempt));}
const response=await fetch('/api/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...values,items:items(),key:attempt.key,receipt:attempt.receipt})});const result=await response.json();if(!response.ok){if(result.rejected)sessionStorage.removeItem('checkout-attempt');throw new Error(result.error);}sessionStorage.removeItem('checkout-attempt');cart.clear();router.push('/order-confirmation/'+result.order_number);
}catch(e){setError(e instanceof Error?e.message:'Your order could not be confirmed. Retry with the same details.');}finally{setPlacing(false);}}
if(!cart.items.length)return <Empty title="Your bag is empty." copy="Add something from the collection to begin checkout." action={<Link href="/shop" className="button">Explore the collection</Link>}/>;
const fields:{key:keyof Form;label:string;auto?:string;type?:string;full?:boolean}[]=[{key:'name',label:'Full name',auto:'name'},{key:'phone',label:'Mobile number',auto:'tel',type:'tel'},{key:'email',label:'Email (optional)',auto:'email',type:'email',full:true},{key:'region',label:'Province / region',auto:'address-level1'},{key:'city',label:'City',auto:'address-level2'},{key:'address',label:'Complete street address',auto:'street-address',full:true},{key:'landmark',label:'Nearby landmark (optional)',full:true},{key:'notes',label:'Order notes (optional)',full:true}];return <form onSubmit={handleSubmit(submit)} className="checkout-grid"><div className="panel stack"><div><p className="eyebrow">01 / Delivery details</p><h2 className="mt-3">Where should it go?</h2></div><div className="fields">{fields.map(f=><label className={f.full?'full':''} key={f.key} htmlFor={f.key}>{f.label}<input id={f.key} type={f.type||'text'} autoComplete={f.auto} {...register(f.key)} aria-invalid={!!errors[f.key]} aria-describedby={errors[f.key]?f.key+'-error':undefined}/>{errors[f.key]&&<span className="error" id={f.key+'-error'}>{errors[f.key]?.message}</span>}</label>)}</div><div className="notice"><strong>Cash on delivery</strong><p>{s.cod_instructions}</p></div><p className="muted">By placing your order, you agree to our <Link href="/terms" className="underline">terms</Link> and <Link href="/privacy" className="underline">privacy policy</Link>.</p>{error&&<p role="alert" className="error">{error}</p>}<button className="button" disabled={placing||quoting||!s.policies_reviewed}>{placing?'Placing your order…':'Place cash on delivery order'}</button>{!s.policies_reviewed&&<p className="notice">Orders will open when the store is ready to launch.</p>}<Link href="/cart">← Return to your bag</Link></div><details className="panel summary" open><summary>Order summary · {cart.items.reduce((n,i)=>n+i.quantity,0)} items</summary><div className="stack">{(quote?.items||cart.items).map((i,n)=><div className="row between" key={n}><span>{i.name} × {i.quantity}</span><span>{money(i.price*i.quantity,s.currency)}</span></div>)}<button className="button secondary" type="button" disabled={quoting||placing} onClick={calculate}>{quoting?'Calculating…':'Calculate delivery & total'}</button>{quote?<><div className="row between"><span>Subtotal</span><span>{money(quote.subtotal,quote.currency)}</span></div><div className="row between"><span>Delivery</span><span>{money(quote.shipping,quote.currency)}</span></div><div className="row between"><strong>Pay on arrival</strong><strong>{money(quote.total,quote.currency)}</strong></div></>:<p className="muted">Enter your destination to calculate delivery. Final prices and stock are checked when you place your order.</p>}<p className="muted">{s.delivery_estimate}</p></div></details></form>;}


