'use client';
import Link from 'next/link';
import Image from 'next/image';
import {useEffect,useState,useRef} from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import {Menu,Search,ShoppingBag,X,ArrowRight,Package,Truck,ShieldCheck,Check} from 'lucide-react';
import {useCart} from '@/lib/cart';
import {money,type Product,type Settings} from '@/lib/model';
import {metaEvent} from './meta-pixel';
export function Drawer({label,children,trigger,open,onOpenChange}:{label:string;children:React.ReactNode;trigger:React.ReactNode;open?:boolean;onOpenChange?:(v:boolean)=>void}){return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Trigger asChild>{trigger}</Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="scrim"/><Dialog.Content className="drawer"><div className="row between"><Dialog.Title>{label}</Dialog.Title><Dialog.Close aria-label="Close" className="icon"><X/></Dialog.Close></div><Dialog.Description className="sr-only">{label} controls</Dialog.Description>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>;}
export function Header({settings:s}:{settings:Settings}){const cart=useCart();const [compact,setCompact]=useState(false);useEffect(()=>{const update=()=>setCompact(window.scrollY>40);window.addEventListener('scroll',update,{passive:true});return()=>window.removeEventListener('scroll',update);},[]);useEffect(()=>{useCart.persist.rehydrate();},[]);return <><div className="announcement"><div className="announcement-track">{["Free delivery across Pakistan",...s.announcement.split("|").map(v=>v.trim()).filter(Boolean)].map((message,index)=><span key={index}>{message}</span>)}</div></div><header className={compact?"header compact":"header"}><div className="wrap header-inner"><div className="mobile"><Drawer label="Explore" trigger={<button className="icon" aria-label="Open menu"><Menu/></button>}><nav className="stack"><Link href="/">Home</Link><Link href="/shop">Shop products</Link><Link href="/collections">Collections</Link><Link href="/about">Our story</Link><Link href="/track">Track an order</Link></nav></Drawer></div><Link href="/" className="wordmark brand-logo" aria-label="Store home"><Image unoptimized src={s.logo||'/pk-trendz-mart-logo.svg'} width={200} height={40} alt={s.brand_name||'PK Trendz Mart'}/></Link><nav className="desktop row"><Link href="/">Home</Link><Link href="/shop">Shop</Link><Link href="/collections">Collections</Link><Link href="/track">Track order</Link><Link href="/about">Our story</Link></nav><form className="header-search desktop" action="/shop"><Search size={17} aria-hidden="true"/><input name="search" aria-label="Search products" placeholder="Search products…"/></form><div className="row utilities"><Link href="/shop?search=" aria-label="Search products" className="icon mobile"><Search size={21}/></Link><Drawer label="Your bag" open={cart.open} onOpenChange={cart.setOpen} trigger={<button className="icon" aria-label={`Shopping bag, ${cart.items.reduce((n,i)=>n+i.quantity,0)} items`}><ShoppingBag size={21}/><span className="count">{cart.items.reduce((n,i)=>n+i.quantity,0)}</span></button>}><CartContent currency={s.currency} drawer/></Drawer></div></div></header></>;}
export function Empty({title='The collection is on its way.',copy='We’re preparing something worth discovering. Check back soon.',action}:{title?:string;copy?:string;action?:React.ReactNode}){return <div className="empty"><div className="empty-icon"><Package size={30} strokeWidth={1}/></div><h2>{title}</h2><p>{copy}</p>{action}</div>;}
export function ProductGrid({products,currency}:{products:Product[];currency:string}){return <div className="product-grid">{products.map(p=>{const image=[...p.product_images].sort((a,b)=>a.position-b.position).find(media=>media.media_type!=='video');return <Link className="product-card" href={'/products/'+p.slug} key={p.id}><div className="product-image">{image?<Image unoptimized fill sizes="(max-width: 767px) 50vw, 25vw" src={image.url} alt={image.alt}/>:<Package size={40} strokeWidth={1}/>}</div><h3>{p.name}</h3><p>{money(p.price,currency)} {p.compare_at&&<del>{money(p.compare_at,currency)}</del>}</p>{p.stock===0&&!p.product_variants.some(v=>v.active&&v.stock>0)&&<span className="stock-badge">Out of stock</span>}</Link>})}</div>;}
export function MagneticLink({href,children}:{href:string;children:React.ReactNode}){return <Link className="magnetic-button" href={href} onPointerMove={e=>{if(e.pointerType==='touch')return;const box=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty('--mx',`${(e.clientX-box.left-box.width/2)*.16}px`);e.currentTarget.style.setProperty('--my',`${(e.clientY-box.top-box.height/2)*.16}px`);}} onPointerLeave={e=>{e.currentTarget.style.setProperty('--mx','0px');e.currentTarget.style.setProperty('--my','0px');}}>{children}<ArrowRight size={17}/></Link>;}
function AddToCartButton({disabled,onAdd,compact=false}:{disabled:boolean;onAdd:()=>void;compact?:boolean}){const [added,setAdded]=useState(false);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);},[]);return <button className={`addly-button${added?' added':''}${compact?' compact-add':''}`} disabled={disabled} onClick={()=>{onAdd();setAdded(true);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>setAdded(false),1200);}} aria-live="polite"><span>{added?'Added to bag':'Add to bag'}</span><span className="addly-icon" aria-hidden="true">{added?<Check/>:<ShoppingBag/>}</span></button>;}
export function Trust({estimate}:{estimate:string}){return <div className="trust wrap"><div><ShieldCheck/><span>Pay on arrival<small>Cash on delivery, made simple</small></span></div><div><Truck/><span>Delivered with care<small>{estimate}</small></span></div><div><Package/><span>Here to help<small><Link href="/contact">Contact our support team</Link></small></span></div></div>;}
export function CartContent({currency,drawer=false}:{currency:string;drawer?:boolean}){const {items,quantity,setOpen}=useCart();if(!items.length)return <Empty title="Your bag has room for something good." copy="Explore the collection and make it yours." action={<Link className="button" href="/shop" onClick={()=>setOpen(false)}>Explore the collection <ArrowRight size={16}/></Link>}/>;return <div className="stack">{items.map((item,index)=><div className="cart-line" key={item.product_id+item.variant_id}>{item.image&&<Image unoptimized src={item.image} width={72} height={90} alt={item.name}/>}<div><Link href={'/products/'+item.slug}>{item.name}</Link><p>{money(item.price,currency)}</p><label>Quantity<input aria-label={'Quantity for '+item.name} type="number" min="1" max="99" value={item.quantity} onChange={e=>quantity(index,Number(e.target.value))}/></label><button className="text-button" onClick={()=>quantity(index,0)}>Remove</button></div></div>)}<div className="row between"><strong>Subtotal</strong><strong>{money(items.reduce((n,i)=>n+i.price*i.quantity,0),currency)}</strong></div><p className="muted">Prices are rechecked and shipping is calculated at checkout.</p><Link className="button" href="/checkout" onClick={()=>setOpen(false)}>Continue to checkout <ArrowRight size={16}/></Link>{drawer&&<Link href="/cart" onClick={()=>setOpen(false)}>View your bag</Link>}</div>;}
export function ProductPurchase({product:p,currency,delivery}:{product:Product;currency:string;delivery:string}){const [variant,setVariant]=useState(p.product_variants.filter(v=>v.active)[0]?.id||'');const [quantity,setQuantity]=useState(1);const [sticky,setSticky]=useState(false);const ref=useRef<HTMLDivElement>(null);const selected=p.product_variants.find(v=>v.id===variant);const stock=selected?.stock??p.stock;const price=selected?.price??p.price;const add=useCart(s=>s.add);useEffect(()=>{const observer=new IntersectionObserver(([e])=>setSticky(!e.isIntersecting&&e.boundingClientRect.top<0));if(ref.current)observer.observe(ref.current);return()=>observer.disconnect();},[]);const buy=()=>{add({product_id:p.id,variant_id:selected?.id||null,quantity,name:p.name+(selected?' / '+selected.name:''),price,image:p.product_images.find(media=>media.media_type!=='video')?.url||'',slug:p.slug});metaEvent('AddToCart',{content_ids:[p.id],content_name:p.name,content_type:'product',value:price*quantity/100,currency,num_items:quantity});};return <><p className="price">{money(price,currency)} {p.compare_at&&<del>{money(p.compare_at,currency)}</del>}</p><p className={stock?'success':'error'}>{stock?'Available · ready to make yours':'Currently unavailable'}</p>{p.product_variants.some(v=>v.active)&&<label>Choose an option<select value={variant} onChange={e=>setVariant(e.target.value)}>{p.product_variants.filter(v=>v.active).map(v=><option key={v.id} value={v.id}>{v.name}{v.stock===0?' — unavailable':''}</option>)}</select></label>}<div ref={ref} className="stack"><label>Quantity<input type="number" min="1" max={Math.min(stock,99)} value={quantity} onChange={e=>setQuantity(Math.max(1,Math.min(99,stock,Number(e.target.value))))}/></label><AddToCartButton disabled={!stock||quantity>stock} onAdd={buy}/><p className="muted">Cash on delivery · {delivery}</p></div>{sticky&&<div className="sticky-buy mobile"><span>{money(price,currency)}</span><AddToCartButton compact disabled={!stock} onAdd={buy}/></div>}</>;}
export function Gallery({product}:{product:Product}){const media=[...product.product_images].sort((a,b)=>a.position-b.position);const [index,setIndex]=useState(0);const active=media[index];return <div><div className="gallery-main">{active?.media_type==='video'?<video src={active.url} controls playsInline preload="metadata" aria-label={active.alt}/>:active?<Image unoptimized fill priority src={active.url} alt={active.alt} sizes="(max-width: 1023px) 100vw, 50vw"/>:<Package size={60} strokeWidth={1}/>}</div><div className="row thumbnails">{media.map((item,i)=><button key={item.id} aria-label={`View ${item.media_type==='video'?'video':'image'} ${i+1}: ${item.alt}`} aria-pressed={index===i} onClick={()=>setIndex(i)}>{item.media_type==='video'?<video src={item.url} muted preload="metadata"/>:<Image unoptimized src={item.url} alt="" width={64} height={80}/>}</button>)}</div></div>;}

