import {createClient} from '@supabase/supabase-js';
const db=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false}});
const keep=['rechargeable-electric-heating-pad-for-period-pain-relief-heated-waist-belly-belt-for-women-girls','🐱-cute-cat-backpack-with-built-in-meow-sound-🔊','vintage-t9-rechargeable-hair-trimmer','automatic-electric-water-blaster-toy','dancing-talking-cactus-toy','5-in-1-rechargeable-blackhead-remover','nova-2-in-1-hair-straightener-curler','2-in-1-electric-straightener-brush'];
const {data:all,error:listError}=await db.from('products').select('id,slug');if(listError)throw listError;
for(const product of all.filter(p=>!keep.includes(p.slug))){const {error}=await db.from('products').update({status:'archived'}).eq('id',product.id);if(error)throw error;}
for(const product of all.filter(p=>keep.includes(p.slug))){const {error}=await db.from('products').update({status:'active'}).eq('id',product.id);if(error)throw error;}
const {data,error:settingsError}=await db.from('store_settings').select('value').eq('id',1).single();if(settingsError)throw settingsError;
const value={...data.value,policies_reviewed:true,hero_product_slug:keep[0],side_banner_one_slug:'dancing-talking-cactus-toy',side_banner_two_slug:'vintage-t9-rechargeable-hair-trimmer',support_email:'pktrendzmart@gmail.com',hero_title:'Comfort, care and clever finds',hero_copy:'Thoughtfully selected products for a more comfortable, beautiful and joyful everyday—with cash on delivery across Pakistan.',hero_link:'/shop',about:'PK Trendz Mart brings together practical, joyful and affordable products for everyday life in Pakistan. We keep the collection focused so every item earns its place.',contact:'Questions about a product, delivery or an existing order? Email our support team at pktrendzmart@gmail.com and include your order reference when applicable.',cod_instructions:'Pay the confirmed total in cash when your order arrives. No advance payment is required.',delivery_estimate:'Our team will confirm delivery timing after your order is placed.',announcement:'Cash on delivery across Pakistan · Nationwide delivery · Secure order tracking'};
const {error:updateError}=await db.from('store_settings').update({value}).eq('id',1);if(updateError)throw updateError;
const {data:active,error:activeError}=await db.from('products').select('name').eq('status','active');if(activeError)throw activeError;console.log(`Store finalized with ${active.length} active products`);
